tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "jmalloc/grit"
tap "dbcli/tap"


brew "cfssl"
brew "curl"
brew "git"
brew "go"
brew "grit"
brew "htop"
brew "midnight-commander"
brew "jmalloc/grit/grit"
brew "jq"
brew "protobuf"
brew "tree"
brew "watch"
brew "vim"
brew "less"
brew "zsh"
brew "zsh-completion"
brew "litecli"
brew "mycli"
brew "pgcli"
brew "gh"
brew "clang-format"


cask "1password-cli"
cask "1password"
cask "docker"
cask "aerial"
cask "google-backup-and-sync"
cask "iterm2"
cask "slack"
cask "tunnelblick"
cask "visual-studio-code"

brew "docker-completion"

mas "Magnet", id: 441258766

