tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "jmalloc/grit"


brew "cfssl"
brew "curl"
brew "git"
brew "go"
brew "grit"
brew "htop"
brew "midnight-commander"
brew "jmalloc/grit/grit"
brew "jq"
brew "protobuf"
brew "tree"
brew "watch"
brew "vim"
brew "less"
brew "unrar"
brew "zsh"

cask "1password-cli"
cask "1password"
cask "docker"
cask "aerial"
cask "google-backup-and-sync"
cask "iterm2"
cask "slack"
cask "tunnelblick"
cask "visual-studio-code"

mas "Magnet", id: 441258766

